### ISSUE TITLE
m.2 ssd is not recognized

### ISSUE THREAD

**Issue by jsparber** [purism/purism-librem-coreboot-updater#2] opened 2017-04-16 12:39 UTC
My m.2 ssd is not recognized, in the boot menu nor in live PureOS 3 and Archlinux. How could I debug this issue? I could not find any errors in dmseg output.
I have a Samsung SM951/NVME SSD.

**Comment by jsparber** [comment] 2017-04-16 20:36
my lspci output the factory bios:
00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
00:1c.2 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #3 (rev e3)
00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
00:1c.5 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #6 (rev e3)
00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03)
00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)
03:00.0 Network controller: Qualcomm Atheros AR9462 Wireless Network Adapter (rev 01)
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller (rev 01)

ls -la /sys/bus/pci/devices
total 0
drwxr-xr-x 2 root root 0 16 apr 21.35 .
drwxr-xr-x 5 root root 0 16 apr 21.35 ..
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:00.0 -> ../../../devices/pci0000:00/0000:00:00.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:02.0 -> ../../../devices/pci0000:00/0000:00:02.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:03.0 -> ../../../devices/pci0000:00/0000:00:03.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:14.0 -> ../../../devices/pci0000:00/0000:00:14.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:16.0 -> ../../../devices/pci0000:00/0000:00:16.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1b.0 -> ../../../devices/pci0000:00/0000:00:1b.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1c.0 -> ../../../devices/pci0000:00/0000:00:1c.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1c.2 -> ../../../devices/pci0000:00/0000:00:1c.2
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1c.3 -> ../../../devices/pci0000:00/0000:00:1c.3
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1c.5 -> ../../../devices/pci0000:00/0000:00:1c.5
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1d.0 -> ../../../devices/pci0000:00/0000:00:1d.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1f.0 -> ../../../devices/pci0000:00/0000:00:1f.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1f.2 -> ../../../devices/pci0000:00/0000:00:1f.2
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:00:1f.3 -> ../../../devices/pci0000:00/0000:00:1f.3
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:02:00.0 -> ../../../devices/pci0000:00/0000:00:1c.2/0000:02:00.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:03:00.0 -> ../../../devices/pci0000:00/0000:00:1c.3/0000:03:00.0
lrwxrwxrwx 1 root root 0 16 apr 21.35 0000:04:00.0 -> ../../../devices/pci0000:00/0000:00:1c.5/0000:04:00.0

I don't know a lot about coreboot and pci, but it seams that the "04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller (rev 01)" is actually  0000:00:1c.5 which is disabled in the devicetree for the librem 13 https://github.com/coreboot/coreboot/blob/6530b6d30dd5197ea855c608cecbcdcea8df9e32/src/mainboard/purism/librem13/devicetree.cb

Is there a reason why the 0000:00:1c.5 is disabled?

**Comment by kakaroto** [comment] 2017-04-18 16:10
Yep, this was the bug we found during internal beta testing just before the Easter holidays. I've ordered an NVMe to test and fix it, and just received it today.
The 1c.5 was disabled because it was thought to be unused. It's re-enabled in my local copy but I didn't push it upstream yet. But even if the NVMe is enabled and working, there remains a problem with seaBios itself which doesn't support booting off of an NVMe device. Actually, it supports it in the git master branch only and only for qemu because "it hasn't been tested on real hardware".
Francois Techene, our beta tester who found the bug initially was able to get it to work for him though. I've built him a new coreboot with 1c.5 enabled and using master seabios with NVMe support enabled and it worked, he had an issue at boot time where it would boot, show the OS bootscreen but never ask him for the password to unlock his drive, so it never finished booting. After he formatted and reinstalled PureOS on his NVMe, it works now without issues for him (he was just about to reinstall anyways).
The question remains: Was the no-password-asked issue caused by his weird 'had-to-be-reinstalled' system or because of coreboot/SeaBios? I think there's still some problem since it was booting fine from the factory bios.
I'm going to send you a similar build for you to test, and if it boots for you, then great, if it doesn't, then we'll know there's more to be fixed in seabios.
anyways, I received my NVMe today, so I'll be testing that for the next few days and we'll know for sure.

**Comment by jsparber** [comment] 2017-04-18 17:20
I can try the new build with the 1c.5 enabled.
Could you provide instruction for building coreboot from source?
Why did you choose seabios instate of grub as payload like libreboot does? Are there advantages?

**Comment by kakaroto** [comment] 2017-04-18 18:34
I've updated the script, it should now load a coreboot with the PCIe #6 enabled (NVMe), it also has SeaBios with NVMe support, and Francois says it works for him, but i'm not getting it to appear here yet (a virgin NVMe SSD, it doesn't show in seabios list, I'm now installing PureOS on it to see if it makes it appear in seabios. Seabios probably doesn't show hard drives with no partitions on them).

As for using grub instead of seabios. No idea, I never tried it (as a payload), and seabios is the default payload with coreboot. If I see that grub supports NVMe well and seabios doesn't, then i'll evaluate grub and maybe switch to it. We could also give the option to the user on which payload they'd like to use.

**Comment by jsparber** [comment] 2017-04-18 19:59
For know the nvme ssd works whenn im booting from a live dongle. Good job ;) 
I can not install grub because it has gpt. And I don' wanna reformat the disk for now. 
I tried to insert in grub, from the usb donge, an entry to load arch from the ssd, but grub can not find the ssd during boot. I don' t know if I do somthing wrong...

Is Francois able to boot from the nvme ssd?

**Comment by kakaroto** [comment] 2017-04-18 20:43
Great. I'm still testing here and it's not going so well... 
I'm using an intel SSD though not a Samsung one like you and Francois have. 
Francois is indeed able to boot from the nvme, but I can't, and I don't know what's the difference.
I can see it in his seabios boot log : 
```
Searching bootorder for: /pci@i0cf8/pci-bridge@1c,5/*@0
....

1. Payload [memtest]
2. USB MSC Drive  USB DISK 3.0 PMAP
3. N1-Samsung SSD 950 PRO 512GB
```

So, here's what you don't understand about installing grub, the 'grub' that would be installed would be a replacement to seabios, so it would be part of coreboot itself and it would be installed on the BIOS ROM, not on the hard drive. So the idea is to have it compiled to act as a bootloader, and I have no idea how it works (would it auto detect drives and usb and show them or it needs a static configuration file written on the ROM?), and I assume once grub boots, it would then boot your hdd-installed grub. 

My current issues is that my NVMe disappears  (similar to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1626894 ) halfway through installing pureOS into the SSD. This happens both with coreboot and the factory BIOS. and of course, Seabios doesn't see the nvme, even though I'm using the same image as francois, but it works for him. It might be related to the specific nvme, but you also have the same (I think) samsung NVMe and it doesn't detect it.

**Comment by jsparber** [comment] 2017-04-18 21:03
About gurb, there are few different ways to install grub:
https://www.coreboot.org/GRUB2
I only know that libreboot uses GRUB as coreboot payload without seaBios.

I have a different SSD (Samsung SM951). In my seabios boot log I see that the pci 1c,5 is enabled, but it gets not recognized as a boot option. The ssd has a gpt table and only systemd-boot installed (means no bios support), I don't now if that makes any difference, it should not. At least it should be recognized as a boot option because also on the other SSD (SATA) I have gpt with no bootloader.

**Comment by kakaroto** [comment] 2017-04-18 21:51
Yeah, thanks for the link.
What libreboot does is grub as a payload, and what I think might be easier for testing is 'grub as a secondary seabios payload', so basically if you use cbfstool to add grub as a payload to coreboot.bin like this (file named grub.bin) : 
```cbfstool coreboot.rom add-payload -n img/grub -f grub.bin -t payload -c LZMA ```
You can also add the grub.cfg with (file named grub.cfg) :
```cbfstool coreboot.rom add -n etc/grub.cfg -f grub.cfg```
Then seabios should show a 'payload [grub] ' option that you can launch to get grub which (hopefully) can load your nvme and boot into it.

**Comment by kakaroto** [comment] 2017-04-21 17:19
Hey, I was busy the last couple of days but today, I finally got some time and I've managed to get seabios to see my NVMe.
I'm still unable to install anything on it (I think a kernel bug makes it disappear during installs), so I can't actually test booting into it, but I'm working on it.
I've updated the script, give it a try now and tell me if you're at least able to boot into yours.

**Comment by jsparber** [comment] 2017-04-22 08:15
With last build I had no problem to boot into my system. The NVMe SSD gets recognized, with out problems, for now. ;). I have now a running system with coreboot + seaBios + Grub (on the NVMe SSD).
Thanks for your fast fixes. It's strange that the ssd disappear on your machine.  I have Linux-libre 4.10.9.

**Comment by kakaroto** [comment] 2017-04-24 16:49
Thanks for the feedback! It's great to know. I still have no idea why it was working for francois, I'm guessing his NVMe might act like a SATA controller too for backward compatibility or something like that. I have no idea.
As for me, the NVMe isn't working on my librem because of some apparent hardware issues. I've tried it on the new prototype for librem 13 v2, and i had no issues there, so I think I have a hardware problem, simple as that... (the librem v1 i have is from an early batch, so I'll blame it on that).
Do you see anything weird in dmesg ? I've found there's a lot of 'AER error' messages appearing in dmesg, so I guess I still need to fix that first before coreboot is ready for the masses.

Thanks for all your testing and feedback! Let me know if you have any more comments.

**Closed by kakaroto** 2017-04-24 16:49 UTC

**Comment by jsparber** [comment] 2017-04-24 17:07
My Librem 13 is also from the first patch, I was one of the first backers. :) so it is strange that you have problems with the nvme. I didn't fond any error related to the ssd in the dmesg. Only thing, it shows that i have a usb Bluetooth device which requires binary blobs which are naturally not included in linux-libre.

**Comment by kakaroto** [comment] 2017-04-24 17:33
Ah ok, interesting, then I suppose I can't trust my system for that. It's possible those AER (PCIe Advanced Error Reporting) messages were there for a good reason and they show my hardware issues (even though they don't appear with factory bios).
The librem I received was from someone in the team, who may have had a pre-release hardware. Internally, it's full of wires that are not there in the final librems, so I think it might have been a prototype. Anyways, thanks for the info. I'll put the nvme stuff to rest for now, hopefully if there's anything still wrong, we'll know during the open beta.

**Comment by kakaroto** [comment] 2017-04-27 18:30
Hey, are you having issues with nvme ? More precisely, if you suspend your computer, does it give errors when you resume or is everything working fine ? Francois is reporting issues with his ssd after a suspend. Wondering if it's an isolated case.

**Comment by jsparber** [comment] 2017-05-01 13:12
I didn't check the dmseg, because i did not expirenced any issues. Nextime use the laptop I will check the dmseg log. Currenty I'm on holidays, so I'm not all the time in front of the computer.

**Comment by jsparber** [comment] 2017-05-04 17:12
Ok I checked the dmseg and I could find any errors. So it seams your problem is a isolated case.

**Comment by kakaroto** [comment] 2017-05-04 17:29
ok, thanks for getting back to! Francois only sees the problem after using his laptop for ~48 hours or so,it happens randomly.

Francois is having issues with his nvme which I think are due to it being actually used as nvme (I think his nvme has a SATA-mode for interoperability with older BIOS, which is why it worked for him initially without nvme support in seabios, but I think that now that it's acting as a real nvme, he's having some additional problems which he didn't have before).
I have also managed to get my nvme to work, and my fix seems to also have fixed the problem Francois was having. 
I think you don't (and never had) those issues possibly because your drive doesn't support the L1.2 power state, I'd like to confirm that, so could you also send me the outputs from these commands (to : youness.alaoui AT puri.sm) :
`cbmem -c `
`lspci -nnxxxvvvvv'

Thanks.

**Comment by jsparber** [comment] 2017-05-04 17:36
Ok I send you the output via mail. What is the L1.2 power state?

**Comment by kakaroto** [comment] 2017-05-04 19:30
Thanks!
L1.2 power state is the lowest power state. You can see it explained here : https://www.synopsys.com/designware-ip/technical-bulletin/reduce-power-consumption.html
It seems to correspond to D3 power state for drives : 
https://msdn.microsoft.com/en-us/library/windows/hardware/ff543186(v=vs.85).aspx

Basically when my NVMe disappears (or when Francois's pc crashes), dmesg always shows a line saying :
`Refused to change power state, currently in D3`
